import React from 'react';

const Footer: React.FC = () => {
  return (
    <footer className="py-6 border-t border-foreground/10">
      <div className="container mx-auto px-4 text-center text-foreground/60">
        <p>&copy; {new Date().getFullYear()}. All rights reserved.</p>
        <p className="text-sm mt-1">Generated by an AI-powered React expert.</p>
      </div>
    </footer>
  );
};

export default Footer;